import type { Sprache } from './i18n';

/** Texte des Generators, im Formular und im Skript gleichermassen genutzt. */
export const GT = {
  de: {
    claim: 'Geld verleihen - aber richtig',
    titel: 'Schuldschein für Dein Privatdarlehen',
    lead: 'Kostenlose Vorlage für ein Darlehen nach §§ 488 ff. BGB, komplett in Deinem Browser ausgefüllt.',
    leadZwei: 'Was Du einträgst, verlässt Dein Gerät nicht.',
    kopfLinks: 'Darlehen unter Privatleuten',
    kopfRechts: 'Pflichtangaben',
    geberName: 'Wer verleiht das Geld?',
    nehmerName: 'Wer leiht es sich?',
    name: 'Vor- und Nachname',
    anschrift: 'Anschrift',
    anschriftHinweis: 'Straße, PLZ, Ort',
    betrag: 'Betrag',
    zurueck: 'Zurück bis',
    unbefristet: 'Kein fester Termin, Kündigung mit drei Monaten Frist',
    auszahlung: 'Wie wird das Geld übergeben?',
    bar: 'bar',
    ueberweisung: 'Überweisung',
    anders: 'anders',
    zwischen: 'Nur wenn Du es brauchst',
    zinsen: 'Zinsen',
    zinssatz: 'Zinssatz pro Jahr in %',
    zinsHinweis: 'leer = zinslos',
    verzugVor: 'Zahlt jemand zu spät, gilt der gesetzliche Verzugszins, derzeit ',
    verzugNach: ' % pro Jahr.',
    warum: 'Warum?',
    raten: 'Rückzahlung in Raten',
    rhythmus: 'Rhythmus',
    einmal: 'in einer Summe',
    monatlich: 'monatlich',
    vierteljaehrlich: 'vierteljährlich',
    ersteRate: 'Erste Rate am',
    ratenHinweis: 'Die Raten rechnen wir aus Betrag, erster Rate und dem Datum bei "Zurück bis" aus.',
    personen: 'Geburtsdaten und Ausweis',
    geburt: 'Geburtsdatum',
    ausweis: 'Ausweisnummer',
    freiwillig: ' (freiwillig)',
    nehmerHinweis: 'Geburtsdatum und Ausweisnummer machen eindeutig, wer das Darlehen erhalten hat.',
    rolleGeber: 'Wer verleiht',
    rolleNehmer: 'Wer sich leiht',
    personenHinweis: 'Hilft, falls es später Streit gibt, wer genau gemeint war. Freiwillig.',
    bank: 'Bankverbindungen',
    ibanGeber: 'Konto für die Rückzahlung',
    ibanNehmer: 'Konto für die Auszahlung',
    ibanHinweis: 'IBAN, beginnt mit DE',
    zweck: 'Wofür ist das Geld?',
    zweckFeld: 'Zweck',
    zweckHinweis: 'zum Beispiel Umzug und Kaution',
    zeuge: 'Zeugin oder Zeuge',
    zeugeHinweis: 'Nicht nötig, macht es aber leichter zu beweisen, dass das Geld übergeben wurde.',
    leeren: 'Formular leeren',
    merken: 'Eingaben auf diesem Gerät merken',
    merkenHinweis: 'Nur in diesem Browser, nie übertragen. Ohne Häkchen ist beim Neuladen alles weg.',
    vorschau: 'So sieht Dein Schuldschein aus',
    kompakt: 'Kompakt',
    ausfuehrlich: 'Ausführlich',
    fassung: 'Fassung',
    unterschreiben: 'Druckt ihn zweimal aus und unterschreibt beide Exemplare von Hand. Ein PDF per Mail ersetzt die Unterschrift nicht.',
    drucken: 'Drucken',
    pdf: 'PDF speichern',
    pdfLaeuft: 'PDF wird erstellt',
    nichtAngegeben: 'nicht angegeben',
    angegeben: 'angegeben',
    zinslos: 'zinslos',
    proJahr: ' % pro Jahr',
    keine: 'keine',
    allesDa: 'Alles Nötige ist da',
    jetzt: 'Jetzt ausdrucken oder als PDF speichern',
    von: ' von ',
    pflichtangaben: ' Pflichtangaben',
    fortschritt: 'Ausgefüllte Pflichtangaben',
    fehlt: 'Es fehlt: ',
    pflicht: {
      geber_name: 'wer verleiht',
      nehmer_name: 'wer sich leiht',
      geber_adresse: 'Anschrift (verleiht)',
      nehmer_adresse: 'Anschrift (leiht sich)',
      summe: 'Betrag',
      zurueck: 'Rückzahlung',
      erste: 'erste Rate',
      nehmer_geburt: 'Geburtsdatum (leiht sich)',
      nehmer_ausweis: 'Ausweisnummer (leiht sich)',
    } as Record<string, string>,
    fehlerBetrag: 'Bitte einen Betrag wie 2.500 oder 2.500,50 eingeben.',
    fehlerIban: 'Diese IBAN stimmt nicht, bitte noch einmal prüfen.',
    fehlerZins: 'Bitte eine Zahl wie 2 oder 2,5 eingeben.',
    fehlerVergangen: 'Das Datum liegt in der Vergangenheit.',
    fehlerRaten: 'Die erste Rate muss vor dem Datum bei "Zurück bis" liegen.',
    datei: 'Schuldschein',
  },
  en: {
    claim: 'Lend money - the right way',
    titel: 'A promissory note for your private loan',
    lead: 'A free template for a loan under §§ 488 ff. of the German Civil Code, filled in entirely in your browser.',
    leadZwei: 'Nothing you enter leaves your device.',
    kopfLinks: 'Loan between private individuals',
    kopfRechts: 'Required',
    geberName: 'Who is lending the money?',
    nehmerName: 'Who is borrowing it?',
    name: 'First and last name',
    anschrift: 'Address',
    anschriftHinweis: 'Street, postcode, town',
    betrag: 'Amount',
    zurueck: 'Repay by',
    unbefristet: "No fixed date, three months' notice",
    auszahlung: 'How is the money handed over?',
    bar: 'cash',
    ueberweisung: 'transfer',
    anders: 'other',
    zwischen: 'Only if you need it',
    zinsen: 'Interest',
    zinssatz: 'Interest rate per year in %',
    zinsHinweis: 'empty = interest-free',
    verzugVor: 'Late payments carry statutory default interest, currently ',
    verzugNach: ' % per year.',
    warum: 'Why?',
    raten: 'Repayment in instalments',
    rhythmus: 'Frequency',
    einmal: 'in one sum',
    monatlich: 'monthly',
    vierteljaehrlich: 'quarterly',
    ersteRate: 'First instalment on',
    ratenHinweis: 'The instalments are calculated from the amount, the first instalment and the "Repay by" date.',
    personen: 'Dates of birth and ID',
    geburt: 'Date of birth',
    ausweis: 'ID card or passport number',
    freiwillig: ' (optional)',
    nehmerHinweis: 'Date of birth and ID number make clear who received the loan.',
    rolleGeber: 'Lender',
    rolleNehmer: 'Borrower',
    personenHinweis: 'Helps if there is ever a dispute about who exactly was meant. Optional.',
    bank: 'Bank accounts',
    ibanGeber: 'Account for repayment',
    ibanNehmer: 'Account for the payout',
    ibanHinweis: 'IBAN',
    zweck: 'What is the money for?',
    zweckFeld: 'Purpose',
    zweckHinweis: 'for example moving costs and deposit',
    zeuge: 'Witness',
    zeugeHinweis: 'Not required, but it makes it easier to prove that the money was handed over.',
    leeren: 'Clear form',
    merken: 'Remember my entries on this device',
    merkenHinweis: 'Only in this browser, never transmitted. Without the tick everything is gone when you reload.',
    vorschau: 'Your promissory note',
    kompakt: 'Short',
    ausfuehrlich: 'Detailed',
    fassung: 'Version',
    unterschreiben: 'Print it twice and both sign each copy by hand. A PDF sent by email does not replace the signature.',
    drucken: 'Print',
    pdf: 'Save PDF',
    pdfLaeuft: 'Creating PDF',
    nichtAngegeben: 'not given',
    angegeben: 'given',
    zinslos: 'interest-free',
    proJahr: ' % per year',
    keine: 'none',
    allesDa: 'Everything required is there',
    jetzt: 'Print it or save it as a PDF',
    von: ' of ',
    pflichtangaben: ' required fields',
    fortschritt: 'Required fields filled in',
    fehlt: 'Missing: ',
    pflicht: {
      geber_name: 'lender',
      nehmer_name: 'borrower',
      geber_adresse: 'address (lender)',
      nehmer_adresse: 'address (borrower)',
      summe: 'amount',
      zurueck: 'repayment',
      erste: 'first instalment',
      nehmer_geburt: 'date of birth (borrower)',
      nehmer_ausweis: 'ID number (borrower)',
    } as Record<string, string>,
    fehlerBetrag: 'Please enter an amount such as 2,500 or 2,500.50.',
    fehlerIban: 'This IBAN is not valid, please check it again.',
    fehlerZins: 'Please enter a number such as 2 or 2.5.',
    fehlerVergangen: 'This date is in the past.',
    fehlerRaten: 'The first instalment must be before the "Repay by" date.',
    datei: 'Promissory-note',
  },
};

export type GeneratorTexte = (typeof GT)[Sprache];
